name: Curl Test

on: [push]

jobs:
  test-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Curl Command
        run: |
          curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mohit-tekwanitr/test-mohittr/codespaces \
            -d '{"ref":"main","machine":"standardLinux32gb"}'
