            name: Create Codespace
            on:
              push:
                branches:
                  - main
            
            jobs:
              create-codespace:
                runs-on: ubuntu-latest
            
                steps:
                  - name: Checkout Repository
                    uses: actions/checkout@v2
            
                  - name: Create Codespace
                    run: |
                      # Access the PAT from GitHub Secrets
                      export GITHUB_TOKEN="${{ secrets.MY_PAT_TOKEN }}"
            
                      # GitHub API URL for creating codespace
                      API_URL="https://api.github.com/repos/mohit-tekwanitr/test-mohittr/codespaces"
            
                      # Define the codespace configuration
                      CODESPACE_CONFIG='{"ref":"main","name":"my-codespace","autoStop":true}'
            
                      # Create codespace using curl
                      curl -v \
                        -X POST \
                        -H "Accept: application/vnd.github.v3+json" \
                        -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "Content-Type: application/json" \
                        -d "$CODESPACE_CONFIG" \
                        "$API_URL"
