name: Curl Test

on:
  push:
    branches:
      - main

jobs:
  test-curl:
    runs-on: ubuntu-latest 

    env:
      FILE_PATH: ${{ secrets.FILE_PATH }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set Up Environment
        run: |
          cd .devcontainer || exit 1
          chmod +x setup-tasks.sh
          
      - name: Run Script
        run: bash .devcontainer/setup-tasks.sh

      - name: Run Curl Command
        run: |
          curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "File-Path: $FILE_PATH" \
            https://api.github.com/repos/mohit-tekwanitr/test-mohittr/codespaces \
            -d '{"ref":"main","machine":"standardLinux32gb"}'
